<?php

/**
 * @file
 * Contains mollo_press.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\mollo_utils\Utility\ViewFilter;
use Drupal\node\Entity\Node;

/**
 * Implements hook_help().
 */
function mollo_press_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mollo_press module.
    case 'help.page.mollo_press':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Artist Module for Mollo Events') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mollo_press_theme() {
  return [
    'mollo_press' => [
      'render element' => 'children',
    ],
  ];
}


function mollo_press_form_alter(&$form, &$form_state, $form_id) {

  // Show Menu with Names on List Filter
  if ($form['#id'] === 'views-exposed-form-mollo-press-admin-list' ||
    $form['#id'] === 'views-exposed-form-mollo-press-visitor-list'

  ) {
    $form = ViewFilter::filter_mollo_event($form);
  }
}
