<?php

/**
 * @file
 * Contains mollo_press.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mollo_press_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the mollo_press module.
    case 'help.page.mollo_press':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Artist Module for Mollo Events') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mollo_press_theme()
{
  return [
    'mollo_press' => [
      'render element' => 'children',
    ],
  ];
}


function mollo_press_form_alter(&$form, &$form_state, $form_id)
{

  // Show Menu with Names on List Filter
  if ($form['#id'] === 'views-exposed-form-mollo-press-admin-list' ||
    $form['#id'] === 'views-exposed-form-mollo-press-visitor-list'

  ) {

    $nids = \Drupal::entityQuery('node')->condition('type', 'mollo_event')->execute();
    $nodes = \Drupal\node\Entity\Node::loadMultiple($nids);
    $options = ['' => 'All'];

    foreach ($nodes as $nid => $node) {
      $value = $node->get('field_mollo_name')->getString();

      if (isset($value)) {
        $options[$value] = $value;
      }
    }

    if (isset($form['event'])) {
      $form['event']['#type'] = 'select';
      $form['event']['#options'] = $options;
      $form['event']['#size'] = 1;
    }
  }
}
